### ISSUE TITLE
Issue with get_historical

### ISSUE THREAD

**Issue by matthewstidham** [lukaszbanasiak/yahoo-finance#128]
I'm able to get a stock price at the moment but the get_historical is not working properly, and I .
![get_historical](https://cloud.githubusercontent.com/assets/26342331/26212505/a5259b7a-3baa-11e7-9e1e-ffc739a93f26.png)

**Comment by knair99** [comment]
I have the same issue as well:
On executing this piece of code:
`
from yahoo_finance import Share as sh
st = sh ('NFLX')
print st.get_historical('2017-05-01', '2017-05-12')`

I get:
    print st.get_historical('2017-05-01', '2017-05-12')
  File "/Library/Python/2.7/site-packages/yahoo_finance/__init__.py", line 342, in get_historical
    result = self._request(query)
  File "/Library/Python/2.7/site-packages/yahoo_finance/__init__.py", line 125, in _request
    raise YQLResponseMalformedError()
yahoo_finance.YQLResponseMalformedError: Response malformed.

-------------
This must be a problem with data tables, since their healthcheck URL does not respond: 
https://www.datatables.org/healthchecker/

**Comment by janrembold** [comment]
The same here:

`Traceback (most recent call last):
  File "/Users/me/anaconda/lib/python3.6/site-packages/yahoo_finance/__init__.py", line 120, in _request
    _, results = response['query']['results'].popitem()
AttributeError: 'NoneType' object has no attribute 'popitem'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/me/anaconda/lib/python3.6/site-packages/yahoo_finance/__init__.py", line 123, in _request
    raise YQLQueryError(response['error']['description'])
KeyError: 'error'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/me/Development/python/broker2/import.py", line 28, in <module>
    data = yahoo.get_historical(date_from, date_to)
  File "/Users/me/anaconda/lib/python3.6/site-packages/yahoo_finance/__init__.py", line 342, in get_historical
    result = self._request(query)
  File "/Users/me/anaconda/lib/python3.6/site-packages/yahoo_finance/__init__.py", line 125, in _request
    raise YQLResponseMalformedError()
yahoo_finance.YQLResponseMalformedError: Response malformed.`

**Comment by junw3i** [comment]
the source of the data tables is from ichart.finance.yahoo.com which is down currently.
https://stackoverflow.com/questions/44030983/yahoo-finance-url-not-working

**Comment by knair99** [comment]
Well, here's a temporary workaround - you can write your own get_history with urllib2, and beautifulsoup.
`
import urllib2
from BeautifulSoup import BeautifulSoup as bs

def get_history(stock):
	url = "https://finance.yahoo.com/quote/" + stock + "/history"
	rows = bs(urllib2.urlopen(url).read()).findAll('table')[1].tbody.findAll('tr')
	for row in rows:
		divs = row.findAll('td')	
		date = divs[0].span.text #date
		open_text = divs[1].span.text #other divs contain 'close', 'high', etc
		if open_text == 'Dividend': #ignore the row with the dividend
			continue
		price_at_open = float(open_text)
		print date, price_at_open

#Test
get_history('AAPL')
`

**Comment by madc0ww** [comment]
Same issue here. Is there any workaround?

**Comment by knair99** [comment]
Here's a possible workaround for some of you:

`import urllib2
from BeautifulSoup import BeautifulSoup as bs

def get_historical_data(name, number_of_days):
	data = []
	base_url_1 = "https://finance.yahoo.com/quote/" 
	base_url_2 = "/history/"

	url = base_url_1 + name + base_url_2

	rows = bs(urllib2.urlopen(url).read()).findAll('table')[1].tbody.findAll('tr')

	for each_row in rows:
		d = {} 
		divs = each_row.findAll('td')
		date_div = divs[0].span.text
		open_text = divs[1].span.text #I'm only interested in 'Open'
		#for other values, play with divs[1 through 5]
		if open_text == 'Dividend': #ignore this row in the table
			continue
		d['Date'] = date_div
		d['Close'] = float(open_text)
		data.append(d)

	return data[:number_of_days]

print get_historical_data('aapl', 15)`

**Comment by hemulin** [comment]
For anyone interested, it seems like the entire functionality of the icharts has been discontinued. See the admin answer [here](https://forums.yahoo.net/t5/Yahoo-Finance-help/ichart-not-working-in-my-app/td-p/253560)

**Comment by lukaszbanasiak** [comment]
Duplicated with https://github.com/herval/yahoo-finance/issues/42

**Comment by lukaszbanasiak** [comment]
@hemulin thx for sharing info from admins

**Comment by jasmine323** [comment]
@knair99 something wrong with your code
Traceback (most recent call last):
  File "/Users/hexiaoran/PycharmProjects/mlceshi/data/ceshi3.py", line 18, in <module>
    for i in get_historical_data('amzn', 5):
  File "/Users/hexiaoran/PycharmProjects/mlceshi/data/ceshi3.py", line 7, in get_historical_data
    rows = bs(urllib2.urlopen(url).read()).findAll('table')[1].tbody.findAll('tr')
IndexError: list index out of range

**Comment by knair99** [comment]
@jasmine323 
They changed the formatting of the HTML since I posted that comment in June. 
See this line? 
`rows = bs(urllib2.urlopen(url).read()).findAll('table')[1].tbody.findAll('tr')`

Change that index to 0 instead and it should give you your output:
`	rows = rows.findAll('table')[0].tbody.findAll('tr')`

I've modified my original code to reflect it, but here's an updated version that's getting me results okay.
`import urllib2
from BeautifulSoup import BeautifulSoup as bs

def get_historical_data(name, number_of_days):
	data = []
	url = "https://finance.yahoo.com/quote/" + name + "/history/"
	rows = bs(urllib2.urlopen(url).read())
	rows = rows.findAll('table')[0].tbody.findAll('tr')

	for each_row in rows:
		divs = each_row.findAll('td')
		if divs[1].span.text  != 'Dividend': #Ignore this row in the table
			#I'm only interested in 'Open' price; For other values, play with divs[1 - 5]
			data.append({'Date': divs[0].span.text, 'Open': float(divs[1].span.text.replace(',',''))})

	return data[:number_of_days]

#Test
print get_historical_data('amzn', 15)
`

**Note**
If they change their HTML again in the future, go to the page, inspect the source and see what changed. This will help you modify the code accordingly

**Comment by libnine** [comment]
Here's a statement from Yahoo: https://forums.yahoo.net/t5/Known-issues-and-updates/Yahoo-Finance-API-disabled/m-p/392760#M14

**Comment by quantitative-technologies** [comment]
@knair99 Any idea why this only goes back 100 days? I'm not familiar with `BeautifulSoup`, but I can see that `urllib2.urlopen(url).read()` has quotes going back one year, but `rows` only has 100.

**Comment by knair99** [comment]
@quantitative-technologies Hm, it looks like they only load 100 rows at a time into the table cells despite the data being sent out, I suspect, to handle pagination. The other rows are loaded 100 at a time on scrolling further down. I'll try working on getting the data another way instead of using BS4 for getting it from the rows.
